version: '3.8'

services:
  # Base de dades MySQL
  mysql:
    image: mysql:8.0
    container_name: pet-game-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pet-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Aplicació Spring Boot
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: pet-game-app
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${G_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8080:8080"
    networks:
      - pet-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: phpMyAdmin per gestionar la BD
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pet-game-phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST:-mysql}
      PMA_PORT: ${PMA_PORT:-3306}
      PMA_USER: ${PMA_USER:-root}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - pet-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  pet-network:
    driver: bridge
