version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: virtual-pets-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: virtual_pets_db
    ports:
      - "3306:3309"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - virtual-pets-network

  backend:
    build: ./src/main/java/backend
    container_name: virtual-pets-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/virtual_pets_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - virtual-pets-network

  frontend:
    build: ./src/main/java//frontend
    container_name: virtual-pets-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    networks:
      - virtual-pets-network

volumes:
  mysql_data:

networks:
  virtual-pets-network:
    driver: bridge
