spring:
  datasource:
    url: jdbc:mysql://mysql:3306/petgame?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: petuser
    password: petpass123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
